language: cpp
dist: xenial
compiler: g++
sudo: required
os:
    - linux

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install libql1-mesa-dev qt512base qt512svg qt512charts-no-lgpl qt512xmlpatterns
  - source /opt/qt512/bin/qt512-env.sh


script:
  - /opt/qt512/bin/qmake PREFIX=/usr
  - make
