version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          name: Install Qt5
          command: |
            sudo apt-get update
            sudo apt-get install libsystemd-dev qtbase5-dev qtdeclarative5-dev qt5-qmake
      - run:
          name: Build dependencies
          command: |
            git clone https://github.com/bartek56/libsystemd-qt
            cd libsystemd-qt 
            cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
            make
            sudo make install
      - run:
          name: Build app
          command: |
            qmake
            make
      - store_artifacts:
          path: test-reports/
          destination: python_app
