version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Qt5
          command: |
            sudo apt-get install libsystemd-dev qtbase5-dev qtdeclarative5-dev qt5-qmake
      - run:
          name: Build app
          command: |
            qmake
