version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          name: Install Qt5
          command: |
            sudo apt-get update
            sudo apt-get install libsystemd-dev qtbase5-dev qtdeclarative5-dev cmake
      - run:
          name: Download googletest
          command: |
            cd UnitTests
            git clone https://github.com/google/googletest
      - run:        
          name: Build dependencies
          command: |
            git clone https://github.com/bartek56/libsystemd-qt
            cd libsystemd-qt 
            mkdir build
            cd build
            cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
            make
            sudo make install
      - run:
          name: Build app by cmake
          command: |
            mkdir buildCmake
            cd buildCmake
            cmake ..
            make
      - run:
          name: Build app by qmake
          command: |
            mkdir buildQmake
            cd buildQmake
            qmake ..
            make
      - run:
          name: Unit Tests
          command: |
            cd buildQmake/UnitTests
            ./UnitTests
